# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: b430bd3ca62c0cce5ecf037d40f7df996c41ebba220db72096ddcdab54d879b9e145875e3c911c75751c6b36ddf1a49e8aa347b81ec62975d2255488c66f742d

test:
  secret_key_base: 7a63201e15ec29b0cfaf0a9b6cd5746b76a5533dfca4b1726a2cbffc808881fd802c4b110c7aa2718fbf1bf50ce86d15f393bd6a39d8ab73814fdce6bd434c77

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
